icons_format = "{icon}"

[theme]
theme = "space-villain"
[theme.overrides]
separator = ""
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome6"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:30) $prev $play $next |} "
player = "brave"
[[block.click]]
button = "left"
cmd = "i3 workspace 9"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "echo \uf09b Git"
interval = "once"
[[block.click]]
button = "left"
cmd = "brave 'github.com/silvanomsjr'"

[[block]]
block = "uptime"
interval = 100

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%A %d/%m/%Y %R', l:pt_BR) "
